# Generated by Django 3.2.6 on 2021-09-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('title', models.CharField(max_length=100, verbose_name='Название комплекта')),
                ('thumbnail', models.ImageField(upload_to='cache/catalog_list/images/upload/', verbose_name='Миниатюра комплекта')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
                ('to_publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название изделия')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('thumbnail', models.ImageField(upload_to='cache/catalog_list/images/upload/', verbose_name='Миниатюра изображения')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена')),
                ('to_publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='SliderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cache/catalog_slider/images/upload/', verbose_name='Изображение')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Изображения изделия')),
            ],
            options={
                'verbose_name': 'Слайд изделия',
                'verbose_name_plural': 'Слайды изделия',
            },
        ),
        migrations.CreateModel(
            name='SliderKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cache/catalog_slider/images/upload/', verbose_name='Изображение')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.kit', verbose_name='Комплект')),
            ],
            options={
                'verbose_name': 'Слайд комплекта',
                'verbose_name_plural': 'Слайды комплекта',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Короткое описание')),
                ('thumbnail', models.ImageField(upload_to='cache/catalog_list/images/upload/', verbose_name='Изображение')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
                ('to_publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Категория изделий',
                'verbose_name_plural': 'Категории изделий',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productcategory', verbose_name='Категория изделия'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='product',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.kit', verbose_name='Комплект изделия'),
        ),
        migrations.CreateModel(
            name='KitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Короткое описание')),
                ('thumbnail', models.ImageField(upload_to='cache/catalog_list/images/upload/', verbose_name='Изображение')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
                ('to_publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Категория комплектов',
                'verbose_name_plural': 'Категории комплектов',
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.kitcategory', verbose_name='Категория комплекта'),
        ),
        migrations.AddField(
            model_name='kit',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.collection', verbose_name='Коллекция'),
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('image', models.ImageField(upload_to='cache/catalog_color/images/upload/', verbose_name='Изображение цвета')),
                ('render', models.ImageField(blank=True, upload_to='cache/catalog_color_render/images/upload/', verbose_name='Рендер цвета')),
                ('recommended', models.BooleanField(default=True, verbose_name='Рекомендуемый цвет')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Цвет изделия')),
            ],
            options={
                'verbose_name': 'Цвет изделия',
                'verbose_name_plural': 'Цвета изделия',
            },
        ),
        migrations.CreateModel(
            name='ColorKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('image', models.ImageField(upload_to='cache/catalog_color/images/upload/', verbose_name='Изображение цвета')),
                ('render', models.ImageField(blank=True, upload_to='cache/catalog_color_render/images/upload/', verbose_name='Рендер цвета')),
                ('recommended', models.BooleanField(default=True, verbose_name='Рекомендуемый цвет')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.kit', verbose_name='Цвет комплекта')),
            ],
            options={
                'verbose_name': 'Цвет комплекта',
                'verbose_name_plural': 'Цвета комплекта',
            },
        ),
    ]
