# Generated by Django 3.2.6 on 2021-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210913_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
