# Generated by Django 3.2.6 on 2021-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210918_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorkit',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета комплекта'},
        ),
        migrations.AlterModelOptions(
            name='colorproduct',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета изделия'},
        ),
        migrations.AlterModelOptions(
            name='sliderkit',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterModelOptions(
            name='sliderproduct',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterField(
            model_name='sliderkit',
            name='image',
            field=models.ImageField(upload_to='cache/catalog_slider/images/upload/', verbose_name='Путь к файлу изображения'),
        ),
        migrations.AlterField(
            model_name='sliderproduct',
            name='image',
            field=models.ImageField(upload_to='cache/catalog_slider/images/upload/', verbose_name='Путь к файлу изображения'),
        ),
    ]
