# Generated by Django 3.2.6 on 2021-08-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('tumbnail', models.ImageField(upload_to='cache/news_index/images/upload/', verbose_name='Изображение')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('to_publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cache/news_index/images/upload/', verbose_name='Изображение')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.project', verbose_name='Фотографии')),
            ],
        ),
    ]
