# Generated by Django 3.2.6 on 2021-08-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_tumbnail_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='cache/news_show/images/upload/', verbose_name='Изображение'),
        ),
    ]
